/**
 *@file Keyboard.hpp
 *@author Siddharth Mishra (brightprogrammer)
 *@date 01/29/2022
 *@brief Provides keyboard scancode sets
 *@copyright BSD 3-Clause License

 Copyright (c) 2022, Siddharth Mishra
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.

 3. Neither the name of the copyright holder nor the names of its
 contributors may be used to endorse or promote products derived from
 this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef KEYCODES_HPP
#define KEYCODES_HPP


// keycodes
enum KeyCode {
    NULL_KEY = 0,
    Q_PRESSED = 0x10,
    Q_RELEASED = 0x90,
    W_PRESSED = 0x11,
    W_RELEASED = 0x91,
    E_PRESSED = 0x12,
    E_RELEASED = 0x92,
    R_PRESSED = 0x13,
    R_RELEASED = 0x93,
    T_PRESSED = 0x14,
    T_RELEASED = 0x94,
    Z_PRESSED = 0x15,
    Z_RELEASED = 0x95,
    U_PRESSED = 0x16,
    U_RELEASED = 0x96,
    I_PRESSED = 0x17,
    I_RELEASED = 0x97,
    O_PRESSED = 0x18,
    O_RELEASED = 0x98,
    P_PRESSED = 0x19,
    P_RELEASED = 0x99,
    A_PRESSED = 0x1E,
    A_RELEASED = 0x9E,
    S_PRESSED = 0x1F,
    S_RELEASED = 0x9F,
    D_PRESSED = 0x20,
    D_RELEASED = 0xA0,
    F_PRESSED = 0x21,
    F_RELEASED = 0xA1,
    G_PRESSED = 0x22,
    G_RELEASED = 0xA2,
    H_PRESSED = 0x23,
    H_RELEASED = 0xA3,
    J_PRESSED = 0x24,
    J_RELEASED = 0xA4,
    K_PRESSED = 0x25,
    K_RELEASED = 0xA5,
    L_PRESSED = 0x26,
    L_RELEASED = 0xA6,
    Y_PRESSED = 0x2C,
    Y_RELEASED = 0xAC,
    X_PRESSED = 0x2D,
    X_RELEASED = 0xAD,
    C_PRESSED = 0x2E,
    C_RELEASED = 0xAE,
    V_PRESSED = 0x2F,
    V_RELEASED = 0xAF,
    B_PRESSED = 0x30,
    B_RELEASED = 0xB0,
    N_PRESSED = 0x31,
    N_RELEASED = 0xB1,
    M_PRESSED = 0x32,
    M_RELEASED = 0xB2,

    // 1,2,3...9,0
    ONE_PRESSED = 0x02,
    NINE_PRESSED = 0x0A,
    ZERO_PRESSED = 0x0B,

    ONE_RELEASED = 0x82,
    NINE_RELEASED = 0x8A,
    ZERO_RELEASED = 0x8B,

    POINT_PRESSED = 0x34,
    POINT_RELEASED = 0xB4,

    FWDSLASH_PRESSED = 0x35,
    FWDSLASH_RELEASED = 0xB5,

    BACKSLASH_PRESSED = 0x2B,
    BACKSLASH_RELEASED = 0xAB,

    BACKSPACE_PRESSED = 0xE,
    BACKSPACE_RELEASED = 0x8E,

    SPACE_PRESSED = 0x39,
    SPACE_RELEASED = 0xB9,

    ENTER_PRESSED = 0x1C,
    ENTER_RELEASED = 0x9C,

    HYPHEN_PRESSED = 0x0C,
    HYPHEN_RELEASED = 0x8C,

    EQUALTO_PRESSED = 0x0D,
    EQUALTO_RELEASED = 0x8B,

    TAB_PRESSED = 0x0F,
    TAB_RELEASED = 0x8F,

    OPENSQBRACKET_PRESSED = 0x1A,
    OPENSQBRACKET_RELEASED = 0x9A,

    CLOSEDSQBRACKET_PRESSED = 0x1B,
    CLOSEDSQBRACKET_RELEASED = 0x9B,

    LCTRL_PRESSED = 0x1D,
    LCTRL_RELEASED = 0x9D,

    SEMICOLON_PRESSED = 0x27,
    SEMICOLON_RELEASED = 0xA7,

    SINGLEQUOTE_PRESSED = 0x28,
    SINGLE_QUOTE_RELEASED = 0xA8,

    BACKTICK_PRESSED = 0x29,
    BACKTICK_RELEASED = 0xA9,

    LSHIFT_PRESSED = 0x2A,
    LSHIFT_RELEASED = 0xAA,

    RSHIFT_PRESSED = 0x36,
    RSHIFT_RELEASED = 0xB6,

    KPDSTAR_PRESSED = 0x37,
    KPDSTAR_RELEASED = 0xB7,

    LALT_PRESSED = 0x38,
    LALT_RELEASED = 0xB8,

    CAPSLOCK_PRESSED = 0x3A,
    CAPSLOCK_RELEASED = 0xBA,

    F1_PRESSED = 0x3B,
    F1_RELEASED = 0xBB,

    F2_PRESSED = 0x3C,
    F2_RELEASED = 0xBC,

    F3_PRESSED = 0x3D,
    F3_RELEASED = 0xBD,

    F4_PRESSED = 0x3E,
    F4_RELEASED = 0xBE,

    F5_PRESSED = 0x3F,
    F5_RELEASED = 0xBF,

    F6_PRESSED = 0x40,
    F6_RELEASED = 0xC0,

    F7_PRESSED = 0x41,
    F7_RELEASED = 0xC1,

    F8_PRESSED = 0x42,
    F8_RELEASED = 0xC2,

    F9_PRESSED = 0x43,
    F9_RELEASED = 0xC3,

    F10_PRESSED = 0x44,
    F10_RELEASED = 0xC4,

    F11_PRESSED = 0x57,
    F11_RELEASED = 0xD7,

    F12_PRESSED = 0x58,
    F12_RELEASED = 0xD8,

    NUMLOCK_PRESSED = 0x45,
    NUMLOCK_RELEASED = 0xC5,

    SCROLLLOCK_PRESSED = 0x46,
    SCROLLLOCK_RELEASED = 0xC6,

    KPD7_PRESSED = 0x47,
    KPD7_RELEASED = 0xC7,

    KPD8_PRESSED = 0x48,
    KPD8_RELEASED = 0xC8,

    KPD9_PRESSED = 0x49,
    KPD9_RELEASED = 0xC9,

    KPDHYPHEN_PRESSED = 0x4A,
    KPDHYPHENLEASED = 0xCA,

    KPD4_PRESSED = 0x4B,
    KPD4_RELEASED = 0xCB,

    KPD5_PRESSED = 0x4C,
    KPD5_RELEASED = 0xCC,

    KPD6_PRESSED = 0x4D,
    KPD6_RELEASED = 0xCD,

    KPDPLUS_PRESSED = 0x4E,
    KPDPLUS_RELEASED = 0xCE,

    KPD1_PRESSED = 0x4F,
    KPD1_RELEASED = 0xCF,

    KPD2_PRESSED = 0x50,
    KPD2_RELEASED = 0xD0,

    KPD3_PRESSED = 0x51,
    KPD3_RELEASED = 0xD1,

    KPD0_PRESSED = 0x52,
    KPD0_RELEASED = 0xD2,

    KPDPOINT_PRESSED = 0x53,
    KPDPOINT_RELEASED = 0xD3,

    ESCAPE_PRESSED = 0x01,
    ESCAPE_RELEASED = 0x81,

    COMMA_PRESSED = 0x33,
    COMMA_RELEASED = 0xB3,
};

#endif // KEYCODES_HPP
